import xml.etree.ElementTree as xml
import urllib2
import md5

wpvdemo_download_url = 'http://ref.wp-types.com/_wpv_demo/demos-index.xml'
response = urllib2.urlopen(wpvdemo_download_url)
html = response.read()
tree = xml.fromstring(html)

f = open('view_demo_text.php','w')
f.write('<?php\n\n')
f.write('/* DO NOT EDIT THIS FILE\n * \n * This file is auto generated by create_views_demo_gettext.py\n */\n\n')
f.write('function wpv_demo_get_tutorial_text($text) {\n')

f.write('  $text_md5 = md5($text);\n')
f.write('  switch($text_md5) {\n')

def write_case(text):
    text = text.encode('utf-8')
    f.write('     case \'' + md5.md5(text).hexdigest() + '\':\n')
    f.write('        $text = __(\'' + text + '\', \'wpvdemo\');\n')
    f.write('        break;\n\n')
    
for site in tree.findall('site'):
    write_case(site.find('title').text)
    write_case(site.find('tagline').text)
    write_case(site.find('tutorial_title').text)
    write_case(site.find('short_description').text)
    
    
f.write('  }\n')
f.write('  return $text;\n')
f.write('}\n')
f.close()






