<?php

/* DO NOT EDIT THIS FILE
 * 
 * This file is auto generated by create_views_demo_gettext.py
 */

function wpv_demo_get_tutorial_text($text) {
  $text_md5 = md5($text);
  switch($text_md5) {
     case 'e949097c0b1568e201f9345c24561863':
        $text = __('Magazine', 'wpvdemo');
        break;

     case 'fecf941d03afa25565c3f41b6948a1d7':
        $text = __('A real live WordPress magazine demo site, built with <img src=\"http://ref.wp-types.com/magazine/wp-content/themes/views_base-magazine/images/tv_small.png\" />', 'wpvdemo');
        break;

     case 'f81860fa93ab772cfc40fd6905fec457':
        $text = __('Create a WordPress Magazine Theme', 'wpvdemo');
        break;

     case '093940bca06861df9fa865e76326265d':
        $text = __('If you want to showoff a lot of content, in different subjects, a magazine themes is your solution. Magazine themes let visitors find what they’re looking for quickly and then zoom-in on their favorite topic. We’ll show you how to build your own customized and unique WordPress magazine theme using Types and Views.', 'wpvdemo');
        break;

     case 'aad30c90084cbda5a8f6896d994d7700':
        $text = __('Real Estates', 'wpvdemo');
        break;

     case '654f5d87026159dd2f93817f4b4808b2':
        $text = __('Another <img src=\"http://ref.wp-types.com/estates/wp-content/themes/views_base_real_estate/images/tv_small.png\" /> Demos Sites site', 'wpvdemo');
        break;

     case '9a301b6e0689482747e5801974b75b4d':
        $text = __('Create a Real Estate WordPress Theme', 'wpvdemo');
        break;

     case '999fda13435ce846244d8ae3ae74552d':
        $text = __('It’s possible to create many different complex websites with Types and Views, without having to carry out any difficult coding. You may think that producing a Real Estate theme is beyond your knowledge, that it might be stretching you a little bit too far – but Types and Views takes care of that for you, letting you concentrate on design while it takes care of all of the work.', 'wpvdemo');
        break;

     case '3e1264a44acff2ebae7804a5b6f92fb1':
        $text = __('Views WooCommerce', 'wpvdemo');
        break;

     case '9570e7d14db4ef4405811036be607dd5':
        $text = __('Just another  <img src=\"http://ref.wp-types.com/views-commerce/wp-content/themes/views_base_commerce/images/tv_small_inv.png\" />  Demos Sites site', 'wpvdemo');
        break;

     case 'e5c8d51288eb06b855d3b954214d69dc':
        $text = __('Views and WooCommerce', 'wpvdemo');
        break;

     case '8f3a9bf49050d6390c0c5dec564c04c3':
        $text = __('Classifieds websites often require complex coding. They involve producing lists, which means that you need to carry out number of databased queries. But don\'t worry - Views can take care of all of that for you! This tutorial will show you how to use Views to carry out a number of database queries using Post Views and Taxonomy Views. It will also introduce you to the wpv-if conditional shortcode so you can output conditional HTML.

Please note that WooCommerce should <strong>NOT</strong> be activated before downloading the demo site. The downloader will activate the plugin and create pages for you.', 'wpvdemo');
        break;

  }
  return $text;
}
