{
  "type": "fixed",
  "width": 12,
  "cssframework": "bootstrap-2",
  "template": "",
  "parent": "",
  "name": "Empty",
  "Rows": [
    {
      "kind": "Row",
      "Cells": [
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        },
        {
          "name": "",
          "cell_type": "spacer",
          "row_divider": 1,
          "content": null,
          "kind": "Cell",
          "cssClass": "span1",
          "cssId": "",
          "tag": "div",
          "width": 1,
          "additionalCssClasses": "",
          "editorVisualTemplateID": ""
        }
      ],
      "cssClass": "row-fixed",
      "name": "Row 2",
      "additionalCssClasses": "",
      "row_divider": 1,
      "layout_type": "fixed",
      "cssId": "",
      "tag": "div",
      "width": 1,
      "editorVisualTemplateID": ""
    }
  ],
  "cssClass": "span12",
  "id": "1208",
  "kind": "Layout",
  "has_child": false,
  "slug": "empty-2-2",
  "cssId": "",
  "tag": "div",
  "row_divider": 1,
  "additionalCssClasses": "",
  "editorVisualTemplateID": ""
}

